eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: onboarding
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/onboarding/**
        - id: billing
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/billing/**
        - id: authService
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/billing/**

management:
  tracing:
    sampling:
      probability: 1.0